### ISSUE TITLE
Consider requiring each array element to be on a new line

### ISSUE THREAD

**Issue by notmessenger** [joshforisha/sl-eslint#1]
```
array = [
    'value'
];

array = [
    {
        a: true
    }
]

array = [
    {
        a: true
    }, {
        b: false
    }
]
```

Need to ensure that code like `which = theKeys[ 'theKey' ]` does not get caught up in the rule.

**Comment by notmessenger** [comment]
How is this rule currently enforced https://github.com/softlayer/ember-style-guide#whitespace?

**Comment by joshforisha** [comment]
Those specific whitespace rules are not being enforced at the moment. We should be able to write a custom rule that covers both without much trouble.
