### ISSUE TITLE
Part style guide part listing rule

### ISSUE THREAD

**Issue by notmessenger** [joshforisha/sl-eslint#9]
https://github.com/juwara0/sl-ember-components/blob/578/tests/integration/components/sl-calendar-test.js#L5 has this code:

```
const testContent = Ember.A([
    {
        date: new Date( 2022, 8, 17 ),
        label: 'Today!'
    }
]);
```

Which throws this error

tests/integration/components/sl-calendar-test.js
    5:27  error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap

It also throws it for 12:35, 63:37, and 103:32 in the same file

How do we want to approach this scenario?

**Comment by joshforisha** [comment]
I don't really agree with removing "new" for Ember.A creation, but it seems like you'd just like the "new-cap" rule removed.

**Comment by notmessenger** [comment]
The problem isn't the rule - it should stay.  The problem is that we reference Ember with a capital "E" which is triggering this rule when not using `new`, which we should not be doing with Ember.A() (see https://github.com/softlayer/sl-ember-components/issues/720#issuecomment-136813688)

**Comment by joshforisha** [comment]
I see.

I've added an exception to the "new-cap" rule for Ember.A().
